### PR TITLE
Include stdarg.h in wasm/Writer.cpp

### PR DESCRIPTION
**Pull request by ElvishJerricco**
As far as I can tell, it just won't build without this.

### CODE REVIEW

**Comment by sbc100** [comment]
Strange... its always worked for.  I guess it would depend on the system libraries one uses to compile against.  I'm on ubuntu/trusty and it gets pulling in from other system libraries.  But its certainly better to IWYU.  Thanks.

**Comment by ElvishJerricco** [comment]
Hm. Well it definitely won't build on NixOS without it. It's entirely possible NixOS is the one in the wrong here, since it does some crazy hacks to compiler toolchains, but it looks like other files in LLVM usually explicitly include either `stdarg.h` or `cstdarg.h`, so I think this is normal.

**Comment by sbc100** [comment]
We are moving the wasm lld work to https://github.com/WebAssembly/lld.  Would you mind sending this PR there?

**Comment by dschuff** [comment]
Actually I opened https://github.com/sbc100/lld/pull/6 for this but then I ended up pushing my local commit that had it when we switched to the WebAssembly repo (https://github.com/WebAssembly/lld/commit/00df3059c494b0dcb04c0e4b45e327f0517ed303). So, it's in already!

**Pull request closed without merging**
